language: r
cache: packages
warnings_are_errors: false

r: 
  - bioc-release
  - bioc-devel

r_packages:
    - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'

bioc_check: false