language: r
cache: packages
warnings_are_errors: false
#r_build_args: "--no-build-vignettes"
#r_check_args: "--no-build-vignettes --ignore-vignettes"
install: travis_wait 20 R CMD check

r:
  - bioc-release

r_packages:
    - covr

bioc_packages:
    - BiocCheck
    - BiocStyle

# safelist
branches:
  only:
  - master

before_install:
  - pip install --user codecov

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

#bioc_check: true