language: r
cache: packages
warnings_are_errors: false

r: 
  - bioc-release
  - bioc-devel

r_packages:
    - covr

# safelist
branches:
  only:
  - master

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

bioc_check: false