language: r
cache: packages
warnings_are_errors: false

r: 
  - bioc-release
  - bioc-devel

r_packages:
    - covr

bioc_packages:
    - BiocCheck

# safelist
branches:
  only:
  - master

before_install:
  - pip install --user codecov

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .