# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GLMM parameter estimation using pseudo-likelihood with a custom covariance matrix
#'
#' Iteratively estimate GLMM fixed and random effect parameters, and variance
#' component parameters using Fisher scoring based on the Pseudo-likelihood
#' approximation to a Normal loglihood. This function incorporates a user-defined
#' covariance matrix, e.g. a kinship matrix for genetic analyses.
#'
#' @param Z mat - sparse matrix that maps random effect variable levels to
#' observations
#' @param X mat - sparse matrix that maps fixed effect variables to
#' observations
#' @param K mat - sparse matrix that defines the known covariance patterns between
#' individual observations. For example, a kinship matrix will then adjust for the
#' known/estimated genetic relationships between observations.
#' @param muvec vec vector of estimated phenotype means
#' @param offsets vec vector of model offsets
#' @param curr_theta vec vector of initial parameter estimates
#' @param curr_beta vec vector of initial beta estimates
#' @param curr_u vec of initial u estimates
#' @param curr_sigma vec of initial sigma estimates
#' @param curr_G mat c X c matrix of variance components
#' @param y vec of observed counts
#' @param u_indices List a List, each element contains the indices of Z relevant
#' to each RE and all its levels
#' @param theta_conv double Convergence tolerance for paramter estimates
#' @param rlevels List containing mapping of RE variables to individual
#' levels
#' @param curr_disp double Dispersion parameter estimate
#' @param REML bool - use REML for variance component estimation
#' @param maxit int maximum number of iterations if theta_conv is FALSE
#' @param solver string which solver to use - either HE (Haseman-Elston regression) or Fisher scoring
#' @param vardist string which variance form to use NB = negative binomial, P=Poisson [not yet implemented]/
#' @param disp_as_vc bool - estimate the negative binomial overdispersion as an
#' additional variance component on the REML objective, rather than by a golden
#' section search on the conditional negative binomial likelihood at the current
#' fitted means. Only implemented for the Fisher solver; the Haseman-Elston
#' solvers fall back to the golden section search with a warning.
#'
#' @details Fit a NB-GLMM to the counts provided in \emph{y}. The model uses an iterative approach that
#' switches between the joint fixed and random effect parameter inference, and the variance component
#' estimation. A pseudo-likelihood approach is adopted to minimise the log-likelihood of the model
#' given the parameter estimates. The fixed and random effect parameters are estimated using
#' Hendersons mixed model equations, and the variance component parameters are then estimated with
#' the specified solver, i.e. Fisher scoring, Haseman-Elston or constrained Haseman-Elston regression. As
#' the domain of the variance components is [0, +\code{Inf}], any negative variance component estimates will
#' trigger the switch to the HE-NNLS solver until the model converges.
#'
#' @return A \code{list} containing the following elements (note: return types are dictated by Rcpp, so the R
#' types are described here):
#' \describe{
#' \item{\code{FE}:}{\code{numeric} vector of fixed effect parameter estimates.}
#' \item{\code{RE}:}{\code{list} of the same length as the number of random effect variables. Each slot contains the best
#' linear unbiased predictors (BLUPs) for the levels of the corresponding RE variable.}
#' \item{\code{Sigma:}}{\code{numeric} vector of variance component estimates, 1 per random effect variable. For this model the
#' last variance component corresponds to the input \emph{K} matrix.}
#' \item{\code{converged:}}{\code{logical} scalar of whether the model has reached the convergence tolerance or not.}
#' \item{\code{Iters:}}{\code{numeric} scalar with the number of iterations that the model ran for. Is strictly <= \code{max.iter}.}
#' \item{\code{Dispersion:}}{\code{numeric} scalar of the dispersion estimate computed off-line}
#' \item{\code{Hessian:}}{\code{matrix} of 2nd derivative elements from the fixed and random effect parameter inference.}
#' \item{\code{SE:}}{\code{matrix} of standard error estimates, derived from the hessian, i.e. the square roots of the diagonal elements.}
#' \item{\code{t:}}{\code{numeric} vector containing the compute t-score for each fixed effect variable.}
#' \item{\code{COEFF:}}{\code{matrix} containing the coefficient matrix from the mixed model equations.}
#' \item{\code{P:}}{\code{matrix} containing the elements of the REML projection matrix.}
#' \item{\code{Vpartial:}}{\code{list} containing the partial derivatives of the (pseudo)variance matrix with respect to each variance
#' component.}
#' \item{\code{Ginv:}}{\code{matrix} of the inverse variance components broadcast to the full Z matrix.}
#' \item{\code{Vsinv:}}{\code{matrix} of the inverse pseudovariance.}
#' \item{\code{Winv:}}{\code{matrix} of the inverse elements of W = D^-1 V D^-1}
#' \item{\code{VCOV:}}{\code{matrix} of the variance-covariance for all model fixed and random effect variable parameter estimates.
#' This is required to compute the degrees of freedom for the fixed effect parameter inference.}
#' \item{\code{CONVLIST:}}{\code{list} of \code{list} containing the parameter estimates and differences between current and previous
#' iteration estimates at each model iteration. These are included for each fixed effect, random effect and variance component parameter.
#' The list elements for each iteration are: \emph{ThetaDiff}, \emph{SigmaDiff}, \emph{beta}, \emph{u}, \emph{sigma}.}
#' }
#'
#' @author Mike Morgan
#'
#' @examples
#' NULL
#'
#' @name fitGeneticPLGlmm
#'
fitGeneticPLGlmm <- function(Z, X, K, muvec, offsets, curr_beta, curr_theta, curr_u, curr_sigma, curr_G, y, u_indices, theta_conv, rlevels, curr_disp, REML, maxit, solver, vardist, disp_as_vc = TRUE) {
    .Call('_miloR_fitGeneticPLGlmm', PACKAGE = 'miloR', Z, X, K, muvec, offsets, curr_beta, curr_theta, curr_u, curr_sigma, curr_G, y, u_indices, theta_conv, rlevels, curr_disp, REML, maxit, solver, vardist, disp_as_vc)
}

#' GLMM parameter estimation using pseudo-likelihood
#'
#' Iteratively estimate GLMM fixed and random effect parameters, and variance
#' component parameters using Fisher scoring based on the Pseudo-likelihood
#' approximation to a Normal loglihood.
#'
#' @param Z mat - sparse matrix that maps random effect variable levels to
#' observations
#' @param X mat - sparse matrix that maps fixed effect variables to
#' observations
#' @param muvec vec vector of estimated phenotype means
#' @param offsets vec vector of model offsets
#' @param curr_theta vec vector of initial parameter estimates
#' @param curr_beta vec vector of initial beta estimates
#' @param curr_u vec of initial u estimates
#' @param curr_sigma vec of initial sigma estimates
#' @param curr_G mat c X c matrix of variance components
#' @param y vec of observed counts
#' @param u_indices List a List, each element contains the indices of Z relevant
#' to each RE and all its levels
#' @param theta_conv double Convergence tolerance for paramter estimates
#' @param rlevels List containing mapping of RE variables to individual
#' levels
#' @param curr_disp double Dispersion parameter estimate
#' @param REML bool - use REML for variance component estimation
#' @param maxit int maximum number of iterations if theta_conv is FALSE
#' @param solver string which solver to use - either HE (Haseman-Elston regression) or Fisher scoring
#' @param vardist string which variance form to use NB = negative binomial, P=Poisson [not yet implemented.]
#' @param disp_as_vc bool - estimate the negative binomial overdispersion as an
#' additional variance component on the REML objective, rather than by a golden
#' section search on the conditional negative binomial likelihood at the current
#' fitted means. Only implemented for the Fisher solver; the Haseman-Elston
#' solvers fall back to the golden section search with a warning.
#'
#' @details Fit a NB-GLMM to the counts provided in \emph{y}. The model uses an iterative approach that
#' switches between the joint fixed and random effect parameter inference, and the variance component
#' estimation. A pseudo-likelihood approach is adopted to minimise the log-likelihood of the model
#' given the parameter estimates. The fixed and random effect parameters are estimated using
#' Hendersons mixed model equations, and the variance component parameters are then estimated with
#' the specified solver, i.e. Fisher scoring, Haseman-Elston or constrained Haseman-Elston regression. As
#' the domain of the variance components is [0, +\code{Inf}], any negative variance component estimates will
#' trigger the switch to the HE-NNLS solver until the model converges.
#'
#' @return A \code{list} containing the following elements (note: return types are dictated by Rcpp, so the R
#' types are described here):
#' \describe{
#' \item{\code{FE}:}{\code{numeric} vector of fixed effect parameter estimates.}
#' \item{\code{RE}:}{\code{list} of the same length as the number of random effect variables. Each slot contains the best
#' linear unbiased predictors (BLUPs) for the levels of the corresponding RE variable.}
#' \item{\code{Sigma:}}{\code{numeric} vector of variance component estimates, 1 per random effect variable.}
#' \item{\code{converged:}}{\code{logical} scalar of whether the model has reached the convergence tolerance or not.}
#' \item{\code{Iters:}}{\code{numeric} scalar with the number of iterations that the model ran for. Is strictly <= \code{max.iter}.}
#' \item{\code{Dispersion:}}{\code{numeric} scalar of the dispersion estimate computed off-line}
#' \item{\code{Hessian:}}{\code{matrix} of 2nd derivative elements from the fixed and random effect parameter inference.}
#' \item{\code{SE:}}{\code{matrix} of standard error estimates, derived from the hessian, i.e. the square roots of the diagonal elements.}
#' \item{\code{t:}}{\code{numeric} vector containing the compute t-score for each fixed effect variable.}
#' \item{\code{COEFF:}}{\code{matrix} containing the coefficient matrix from the mixed model equations.}
#' \item{\code{P:}}{\code{matrix} containing the elements of the REML projection matrix.}
#' \item{\code{Vpartial:}}{\code{list} containing the partial derivatives of the (pseudo)variance matrix with respect to each variance
#' component.}
#' \item{\code{Ginv:}}{\code{matrix} of the inverse variance components broadcast to the full Z matrix.}
#' \item{\code{Vsinv:}}{\code{matrix} of the inverse pseudovariance.}
#' \item{\code{Winv:}}{\code{matrix} of the inverse elements of W = D^-1 V D^-1}
#' \item{\code{VCOV:}}{\code{matrix} of the variance-covariance for all model fixed and random effect variable parameter estimates.
#' This is required to compute the degrees of freedom for the fixed effect parameter inference.}
#' \item{\code{CONVLIST:}}{\code{list} of \code{list} containing the parameter estimates and differences between current and previous
#' iteration estimates at each model iteration. These are included for each fixed effect, random effect and variance component parameter.
#' The list elements for each iteration are: \emph{ThetaDiff}, \emph{SigmaDiff}, \emph{beta}, \emph{u}, \emph{sigma}.}
#' }
#'
#' @author Mike Morgan
#'
#' @examples
#' NULL
#'
#' @name fitPLGlmm
fitPLGlmm <- function(Z, X, muvec, offsets, curr_beta, curr_theta, curr_u, curr_sigma, curr_G, y, u_indices, theta_conv, rlevels, curr_disp, REML, maxit, solver, vardist, disp_as_vc = TRUE) {
    .Call('_miloR_fitPLGlmm', PACKAGE = 'miloR', Z, X, muvec, offsets, curr_beta, curr_theta, curr_u, curr_sigma, curr_G, y, u_indices, theta_conv, rlevels, curr_disp, REML, maxit, solver, vardist, disp_as_vc)
}

#' Fit a NB-GLMM with a genetic random effect, optionally warm-started
#'
#' Fits the negative binomial generalised linear mixed model used by Milo for
#' genetic analyses, using penalised quasi-likelihood (PQL) with REML or ML
#' estimation of the variance components. It follows the same iterative logic as
#' \code{fitGeneticPLGlmm} - alternating between the fixed/random effect
#' solutions and the variance component update, with an off-line golden-section
#' search for the dispersion - but differs in three respects that matter for
#' genome-wide use:
#'
#' \enumerate{
#' \item The genetic covariance enters as \eqn{\sigma_g K} directly rather than
#' through a dense \eqn{n \times n} Cholesky block appended to \emph{Z}. This
#' applies \emph{K} exactly once and removes the dominant \eqn{O(n^3)} term.
#' \item The working weight matrices \emph{D} and \emph{W} are diagonal by
#' construction and are carried as vectors, so they are never inverted by a
#' dense LU factorisation.
#' \item Null model parameter estimates may be supplied, in which case they are
#' used as starting values and - if \code{fix_variance} is \code{TRUE} - the
#' variance components and dispersion are held fixed while only the fixed
#' effects are updated.
#' }
#'
#' When \code{return_projection} is \code{TRUE} the REML projection matrix
#' \emph{P} and the vector \eqn{P y^*} are returned. These are the sufficient
#' quantities for the score test in \code{\link{scoreTestGeneticSNPs}}, and are
#' invariant across the SNPs tested within a neighbourhood.
#'
#' @param Z mat - design matrix mapping the levels of the non-genetic random
#' effects to observations. May have zero columns if the genetic random effect
#' is the only one.
#' @param X mat - design matrix of fixed effects. For a null model this excludes
#' the genetic variant of interest.
#' @param K mat - the n x n genetic relationship matrix.
#' @param muvec vec - vector of starting values for the phenotype means.
#' @param offsets vec - vector of model offsets, e.g. log library sizes.
#' @param curr_beta vec - starting values for the fixed effect parameters.
#' @param curr_u vec - starting values for the random effect BLUPs, ordered as
#' the non-genetic effect levels followed by the n genetic effect levels.
#' @param curr_sigma vec - starting values for the variance components. The
#' final element is always the genetic variance component attached to \emph{K}.
#' @param y vec - vector of observed counts.
#' @param u_indices List - each element holds the (1-based) column indices of
#' \emph{Z} belonging to one non-genetic random effect.
#' @param theta_conv double - convergence tolerance on the parameter estimates.
#' @param curr_disp double - starting value for the dispersion.
#' @param REML bool - use REML rather than ML for the variance components.
#' @param maxit int - maximum number of PQL iterations.
#' @param Kinv_ Nullable NumericMatrix - optional precomputed inverse of
#' \emph{K}. \emph{K} is invariant across neighbourhoods and SNPs, so supplying
#' the inverse once avoids repeating an O(n^3) factorisation per model fit.
#' @param null_sigma_ Nullable NumericVector - optional variance components from
#' a previously fitted null model, used as starting values.
#' @param null_beta_ Nullable NumericVector - optional fixed effect estimates
#' from a previously fitted null model, used as starting values. Only the
#' leading elements shared with the current design are used.
#' @param null_disp double - optional dispersion estimate from a previously
#' fitted null model. A negative value means no estimate is supplied.
#' @param fix_variance bool - hold the variance components and dispersion fixed
#' at their supplied values and update only the fixed effects.
#' @param return_projection bool - return the REML projection matrix \emph{P}
#' and \eqn{P y^*}.
#' @param fix_dispersion bool - hold the dispersion fixed at \code{curr_disp}
#' rather than re-estimating it inside the PQL loop. Recommended when a
#' dispersion estimated across neighbourhoods is available, e.g. from
#' \code{edgeR::estimateDisp}.
#' @param max_disp double - upper bound on the size parameter when it is
#' estimated inside the loop. Prevents the search running away to the Poisson
#' limit.
#' @param disp_as_vc bool - estimate the negative binomial overdispersion as an
#' additional variance component on the REML objective, rather than by a
#' golden-section search on the conditional negative binomial likelihood. This
#' puts the overdispersion and the random effect variances on a common
#' objective so that they compete properly. Defaults to \code{TRUE}; set to
#' \code{FALSE} to use the golden-section search on the conditional negative
#' binomial likelihood instead.
#'
#' @details The model fitted is the same pseudo-likelihood approximation used
#' throughout Milo. At convergence the working response is
#' \eqn{y^* = \eta + D^{-1}(y - \mu)} and the pseudo-variance is
#' \eqn{V^* = W + \sum_j \sigma_j Z_j Z_j' + \sigma_g K}, with
#' \eqn{W = \mathrm{diag}(\phi^{-1} + \mu_i^{-1})}. Variance components are
#' updated by Fisher scoring on the REML log-likelihood and constrained to be
#' non-negative.
#'
#' @return A \code{list} containing the fitted model. Elements are:
#' \describe{
#' \item{\code{FE}:}{\code{numeric} vector of fixed effect estimates.}
#' \item{\code{RE}:}{\code{numeric} vector of random effect BLUPs.}
#' \item{\code{Sigma}:}{\code{numeric} vector of variance component estimates, genetic component last.}
#' \item{\code{Dispersion}:}{\code{numeric} scalar dispersion estimate.}
#' \item{\code{converged}:}{\code{logical} whether the convergence tolerance was met.}
#' \item{\code{Iters}:}{\code{numeric} number of PQL iterations run.}
#' \item{\code{SE}:}{\code{numeric} vector of fixed effect standard errors.}
#' \item{\code{t}:}{\code{numeric} vector of Wald t-statistics for the fixed effects.}
#' \item{\code{P}:}{\code{matrix} REML projection matrix, or a 1 x 1 zero matrix if not requested.}
#' \item{\code{Pystar}:}{\code{numeric} vector \eqn{P y^*}, or a length-1 zero vector if not requested.}
#' \item{\code{ystar}:}{\code{numeric} working response at convergence.}
#' \item{\code{Wdiag}:}{\code{numeric} diagonal of the working weight matrix.}
#' \item{\code{VCOV}:}{\code{matrix} variance-covariance matrix of the fixed effects.}
#' \item{\code{LOGLIHOOD}:}{\code{numeric} pseudo-log-likelihood at convergence.}
#' }
#'
#' @author Mike Morgan
#'
#' @examples
#' NULL
#'
#' @name fitGeneticNullGlmm
#'
fitGeneticNullGlmm <- function(Z, X, K, muvec, offsets, curr_beta, curr_u, curr_sigma, y, u_indices, theta_conv, curr_disp, REML, maxit, Kinv_ = NULL, null_sigma_ = NULL, null_beta_ = NULL, null_disp = -1.0, fix_variance = FALSE, return_projection = TRUE, fix_dispersion = FALSE, max_disp = 1e4, disp_as_vc = TRUE) {
    .Call('_miloR_fitGeneticNullGlmm', PACKAGE = 'miloR', Z, X, K, muvec, offsets, curr_beta, curr_u, curr_sigma, y, u_indices, theta_conv, curr_disp, REML, maxit, Kinv_, null_sigma_, null_beta_, null_disp, fix_variance, return_projection, fix_dispersion, max_disp, disp_as_vc)
}

#' Score test for genetic variants against a fitted null model
#'
#' Computes score (Rao) test statistics for a block of genetic variants against
#' a null NB-GLMM fitted by \code{\link{fitGeneticNullGlmm}}. Because the
#' variance components do not depend on the variant being tested, the REML
#' projection \emph{P} and the vector \eqn{P y^*} are computed once per
#' neighbourhood and reused across every variant.
#'
#' For a variant with genotype vector \emph{g} the score statistic is
#' \eqn{U = g' P y^*} with variance \eqn{I = g' P g}, giving
#' \eqn{\chi^2_1 = U^2 / I}. The corresponding one-step effect size estimate is
#' \eqn{\hat{\beta} = U / I} with standard error \eqn{1/\sqrt{I}}, so the Wald
#' statistic formed from these is algebraically identical to the score
#' statistic. Variants are processed as a block so that \eqn{P G} is a single
#' matrix-matrix product rather than a loop of matrix-vector products.
#'
#' @param P mat - the REML projection matrix from the fitted null model.
#' @param Pystar vec - the vector \eqn{P y^*} from the fitted null model.
#' @param G mat - an n x B matrix of genotypes, one column per variant.
#' @param min_variance double - variants whose score variance falls below this
#' value are returned as \code{NA} rather than producing an unstable ratio.
#' This traps monomorphic variants and variants that are collinear with the
#' fixed effects.
#'
#' @details The score test uses the variance components estimated under the
#' null. This is the standard approximation used by genome-wide mixed model
#' methods and is asymptotically equivalent to the Wald test from a full refit;
#' variants passing a screening threshold should be refitted exactly with
#' \code{\link{fitGeneticNullGlmm}} to obtain final effect size estimates.
#'
#' @return A \code{list} with one element per statistic, each a \code{numeric}
#' vector of length B:
#' \describe{
#' \item{\code{Score}:}{the score \eqn{U = g' P y^*}.}
#' \item{\code{Variance}:}{the score variance \eqn{I = g' P g}.}
#' \item{\code{Chisq}:}{the test statistic \eqn{U^2 / I} on 1 degree of freedom.}
#' \item{\code{Beta}:}{the one-step effect size estimate \eqn{U / I}.}
#' \item{\code{SE}:}{the standard error \eqn{1/\sqrt{I}}.}
#' }
#'
#' @author Mike Morgan
#'
#' @examples
#' NULL
#'
#' @name scoreTestGeneticSNPs
#'
scoreTestGeneticSNPs <- function(P, Pystar, G, min_variance = 1e-12) {
    .Call('_miloR_scoreTestGeneticSNPs', PACKAGE = 'miloR', P, Pystar, G, min_variance)
}

